# Generated by Django 4.2.11 on 2024-08-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Status", models.BooleanField()),
                ("User_id", models.CharField(max_length=255)),
                ("Email_id", models.EmailField(max_length=254)),
                ("roll", models.CharField(max_length=255)),
                ("numbers", models.CharField(max_length=255)),
                ("alphabets", models.CharField(max_length=255)),
                ("highest_alphabet", models.CharField(max_length=255)),
            ],
        ),
    ]
