# Generated by Django 4.2.11 on 2024-08-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="Email_id",
            field=models.EmailField(
                default="manojkumar_tadekoru@srmap.edu.in", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="details",
            name="Status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="details",
            name="User_id",
            field=models.CharField(default="manojkumar", max_length=255),
        ),
        migrations.AlterField(
            model_name="details",
            name="roll",
            field=models.CharField(default="AP21110010342", max_length=255),
        ),
    ]
