# Generated by Django 4.2.11 on 2024-08-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bapp", "0002_alter_details_email_id_alter_details_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="Email_id",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="details", name="Status", field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="details",
            name="User_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="details",
            name="alphabets",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="details",
            name="highest_alphabet",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="details",
            name="numbers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="details", name="roll", field=models.CharField(max_length=255),
        ),
    ]
